### ISSUE TITLE
[anagnoes] Boost test exercise

### ISSUE THREAD

**Issue by EvanA93** [Simulation-Software-Engineering/testing-boost-exercise#15]
Pull-Request-LInk: https://github.com/EvanA93/testing-boost-exercise/pull/1

**Comment by uekerman** [comment]
Sorry for the late feedback! Looks good :+1:
To make the action output easier to skim, you could install all dependencies in one step and give names to the steps
```yml
...
- name: "Install dependencies"
  run: sudo apt update && sudo apt install libboost-test-dev libeigen3-dev libyaml-cpp-dev
- name: "Run tests"
...
```
